version: 2

jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - test
