version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Testing
          command: npm test

  publish:
    docker:
      - image: pnedelko/circleci-node-8-awscli:1.0.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Publishing to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish
      - run:
          name: Uploading to S3
          command: aws s3 sync ./dist s3://elasticio-cdn-eu/vendor/jsonata-moment/`npm view @elastic.io/jsonata-moment version`

workflows:
  version: 2
  build:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
      - publish:
          requires:
            - hold
          filters:
            branches:
              only: master
